language: python
env:
  global:
    - MAKAHIKI_DATABASE_URL=postgres://postgres@127.0.0.1:5432/makahiki
    - MAKAHIKI_ADMIN_INFO=admin:admin
    - MAKAHIKI_DEBUG=True
postgres:
    adapter: postgresql
    database: makahiki
    username: postgres
before_install:
    - sudo apt-get install libjpeg8 libjpeg8-dev libfreetype6 libfreetype6-dev zlib1g-dev tree python-imaging
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so.8 /usr/lib
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib
install: 
    - pip install -r requirements.txt --use-mirrors --quiet
    - pip install -U selenium

before_script:
    - psql -c 'create user makahiki;' -U postgres
    - psql -c 'create database makahiki owner makahiki;' -U postgres
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"  
script: coverage run --source=makahiki/apps/ makahiki/manage.py test
after_script:
    - coverage report -m
    - cd makahiki;
    - scripts/run_pylint.sh
    - scripts/run_pep8.sh
notifications:
    email:
        - cammymoore07@gmail.com